main = ".open-next/worker.js"
name = "getclay"
compatibility_date = "2025-03-25"
compatibility_flags = ["nodejs_compat"]

[build]
command = "bun run build:cloudflare"

[assets]
directory = ".open-next/assets"
binding = "ASSETS"
[[d1_databases]]
binding = "DB"
database_name = "getclay_beta"
database_id = "f054140b-bc15-4df6-b181-0cb2894d3c71"

[observability.logs]
enabled = true

